### ISSUE TITLE
related to wemod unlocker

### ISSUE THREAD

**Issue by Sensei412** [bennett-sh/gh-clone-button#1]
hey you think you could create a matrix group and upload your wemod unlockers there? cant believe these assholes took it down. sorry for putting this here but you have no contact.

**Comment by bennett-sh** [comment]
Hey, thanks for the interest however because I don't want to get into any
further legal trouble, I will not continue on distributing the requested
piece of software again.

*DISCLAIMER*: Everything mentioned in the following section is either for
educational purposes only or should only be done if WeMod has given you
permission to do so because it otherwise could get you in trouble. I
personally do not have this permission so I'm not doing anything stated
below.


You may still find WMPU on GitHub from different users (they'll be taken
down soon as I'll probably write them about it).
If you want to know how it worked (not for recreating it!), you can look at
the takedown information provided by GitHub.

**Comment by bennett-sh** [comment]
Hey, thanks for the interest however because I don't want to get into any
further legal trouble, I will not continue on distributing the requested
piece of software again.
